name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: aldoborrero/use-nix-action@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: bun run tauri build

