name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        if: matrix.os == 'ubuntu-latest'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: HatsuneMiku3939/direnv-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          direnvVersion: 2.33.0
      - name: Build
        run: bun run tauri build

